# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_MINI_PROJECT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_MINI_PROJECT
pod 'Toast-Swift', '~> 5.0.0'
end
